languageCode = "en-ca"
baseURL = "https://www.uric.ca/" #
theme = "boot"
relativeURLs = true
googleAnalytics = "UA-165627404-2" # Your Analytics ID here
disableKinds = ["taxonomy", "taxonomyTerm"]

title = "Ucluelet Rent-It Center"
description = "With our professional-grade & well-stocked inventory, Ucluelet Rent-It Center offers tool rental, small and large equipment rental services for you to get the job done."

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
    

    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2

    [[menu.main]]
        name = "Services"
        url = "/services/"
        weight = 3

    [[menu.main]]
        name = "Sales"
        url = "/sales/"
        weight = 4

    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 5

    [[menu.main]]
        name = "RENT NOW"
        url = "https://uric.ezrentalstore.com"
        weight = 6


[params]
    # Schema Information
    businessname = "Ucluelet Rent-It Center"
    greatquote = "The one stop shop for all your construction or renovation needs"
    type = "HomeAndConstructionBusiness" # Enter Your Type of business - schema.org
    pricerange = "2" # Enter Your Price range 1 to 5
    reviewcount = "8" # How many reviews you've got
    reviewvalue = "4.4" # Average ratings on Yelp & Google
    reservation = "false" # Do you accept reservations? Enter true or false
    openinghour = "'Mon - Fri 8AM - 5PM, Saturdays 9AM - 3PM, Sunday - CLOSED, STAT Holidays - CLOSED'" # Opening Hours
    address = "317 Forbes Road" # Enter Address Here
    city = "Ucluelet" # Enter City
    region = "BC" # Enter State or Province Here
    country = "Canada" #Enter Country Here
    postalcode = "V0R 3A0" # Enter Postal Code
    phone = "+1-250-726-7368" # Enter Phone Number
    email = "info@uric.ca" # Enter Your Email
    facebookurl = "https://www.facebook.com/UclueletRentItCenterLtd"
    instagram = "https://instagram.com/"
    logo = "img/logo.jpg"
    image = "img/og.jpg" # Ideal 1200 x 630 for schema + og
    alt = "Ucluelet Rent-It Center"
